import { Preahvihear } from "next/font/google";
import "./globals.css";

const preahvihear = Preahvihear({ subsets: ["latin"], weight: "400" });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={preahvihear.className}>{children}</body>
    </html>
  );
}
